### ISSUE TITLE
The linux-node-gui fails regularly, and don't reinit

### ISSUE THREAD

**Issue by jmarunix** [noia-network/noia-node-cli#13]
**Describe the bug**
The linux-node-gui fails regularly, and don't reinit. And to see the output error I tried to launch from console to view what happen, and this is the result.

**To Reproduce**
1. From console, launch the app via ./noia-node-gui-0.6.0-linux-x86_64.AppImage
2. The final error shows:
Update` for version 0.6.0 is not available (latest version: 0.6.0, downgrade is disallowed).
internal/process.js:103
    memoryUsage_(memValues);
    ^

Error: EMFILE: too many open files, uv_resident_set_memory
    at process.memoryUsage (internal/process.js:103:5)
    at Object.exception.getProcessInfo (/tmp/.mount_noia-nWllmbM/resources/app.asar/node_modules/winston/lib/winston/exception.js:33:26)
    at Object.exception.getAllInfo (/tmp/.mount_noia-nWllmbM/resources/app.asar/node_modules/winston/lib/winston/exception.js:17:24)
    at exports.Logger.Logger._uncaughtException (/tmp/.mount_noia-nWllmbM/resources/app.asar/node_modules/winston/lib/winston/logger.js:636:24)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.emit (/tmp/.mount_noia-nWllmbM/resources/app.asar/node_modules/electron-updater/node_modules/source-map-support/source-map-support.js:454:21)
    at process._fatalException (bootstrap_node.js:383:26)

**Expected behavior**
-- A clear and concise description of what you expected to happen. --

**Screenshots**
-- If applicable, add screenshots to help explain your problem. --

**Info:**
 - OS: Fedora 4.17.19-200.fc28.x86_64 #1 SMP Fri Aug 24 15:47:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - Node.js version: v8.11.4
 - App version 0.6.0

**Additional context**
-- Add any other context about the problem here. --

**Comment by MartynasZilinskas** [comment]
Latest version of CLI is v0.2.3. Did you meant GUI?

**Comment by jmarunix** [comment]
Yes, excuse me @MartynasZilinskas
