### ISSUE TITLE
noia node cli error spawnSync ip ENOENT

### ISSUE THREAD

**Issue by tobg** [noia-network/noia-node-cli#18]
Ubuntu 18.04, node 10.15.3

got the following error:

info: [noia-node] Initializing NOIA node, settings-path=/home/noia/.noia-node/node.settings.
(node:346) UnhandledPromiseRejectionWarning: Error: spawnSync ip ENOENT
    at Object.spawnSync (internal/child_process.js:990:20)
    at Object.spawnSync (child_process.js:601:24)
    at Function.module.exports.sync (/home/noia/noia-node-cli/node_modules/default-gateway/node_modules/execa/index.js:337:30)
    at sync (/home/noia/noia-node-cli/node_modules/default-gateway/linux.js:50:24)
    at Function.module.exports.v4.sync (/home/noia/noia-node-cli/node_modules/default-gateway/linux.js:57:32)
    at Function.module.exports.v4.sync (/home/noia/noia-node-cli/node_modules/default-gateway/index.js:17:46)
    at new NatPmp (/home/noia/noia-node-cli/node_modules/@noia-network/node/dist/nat-pmp.js:11:43)
    at new ClientSockets (/home/noia/noia-node-cli/node_modules/@noia-network/node/dist/client-sockets.js:17:28)
    at Node.<anonymous> (/home/noia/noia-node-cli/node_modules/@noia-network/node/dist/node.js:67:34)
    at Generator.next (<anonymous>)
(node:346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:346) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by maaft** [comment]
**Solution**
Set ´natPmp=false` in `~/.noia-node/node.settings`
